### ISSUE TITLE
What to do in this case?

### ISSUE THREAD

**Issue by FezVrasta** [rstacruz/rscss#13]
Hey, great project!

I've a navbar with two rows and each row has columns.

Is this correct or should I use something different?

```
.top-navbar
  .subnavbar-one
    .column
    .column
  .subnavbar-two
    .column
    .column
```

**Comment by FezVrasta** [comment]
Maybe in this way is better?

```
.top-navbar
  .subnavbar.-one
    .column
    .column
  .subnavbar.-two
    .column
    .column
```

**Comment by rstacruz** [comment]
I'm going to go with the first one: each subnav probably deserves to be its own component.
