### ISSUE TITLE
Conventions about space between blocks?

### ISSUE THREAD

**Issue by FezVrasta** [rstacruz/rscss#14]
I think it would be useful to define some conventions about the spaces between code block in SASS and LESS.

For example:

``` less
.my-component {
  color: blue;
  > .element1 {
    color: blue;
    &.-active {
      color: blue;
    }
  }
  > .element2 {
    color: blue;
  }
}
```

or

``` less
.my-component {
  color: blue;

  > .element1 {
    color: blue;
    &.-active {
      color: blue;
    }
  }

  > .element2 {
    color: blue;
  }
}
```

?

**Comment by mcgwiz** [comment]
IMHO things like that are too low-level for this type of high-level, macroscopic guidance. Also, that's a slippery slope to a whole world of arbitrary detail: order of properties, tabs vs spaces, opening brace on same line or new line, etc... The value of this doc is that it's tightly-focused on high-level organizational methods, and that gives the added benefit of making it nice and short. Teams are free to layer on whatever low-level rules they prefer.

**Comment by rstacruz** [comment]
I agree — rscss makes no notes on how to do your syntax, there are [other styleguides](https://css-tricks.com/sass-style-guide/) that take care of that.
