### ISSUE TITLE
Pseudo selectors

### ISSUE THREAD

**Issue by nicolo-ribaudo** [rstacruz/rscss#16]
Are pseudo-selectors like `:nth-child` ok? Or it is better to use variants (`-top`, `-bottom`)?

**Comment by rstacruz** [comment]
I don't see why not... using classnames (`-alpha`? `-omega`?) would probably only needlessly  complicate things.

**Comment by stramel** [comment]
@rstacruz Do you take psuedo selectors into account for nesting rules?
