### ISSUE TITLE
Naming mixins

### ISSUE THREAD

**Issue by srph** [rstacruz/rscss#19]
So, I have a generic `btn` mixin.

``` scss
@mixin btn() {
  /* */
}
```

How do you suggest I name its modifiers? Or should I just accept arguments?

**Comment by rstacruz** [comment]
It's a bit hard to give an answer without knowing more about the context of your mixin.

**Comment by srph** [comment]
Let's say if I were to have something like bootstrap `btn`s.

If I wasn't using a preprocessor, I'd probably have these selectors:

``` css
.btn { 
  /* insert generic / default bootstrap btn */
}

.btn.-success { /* green colored-button */ } 
.btn.-danger { /* red colored-button */ } 
.btn.-warning { /* yellow colored-button */ } 
.btn.-info { /* blue colored-button */ } 
```

If I were to use a preprocessor, and use mixins instead of selectors (we can use .extend, but I doubt it's effective in this case, since we can't extend nested selectors):

``` scss
@mixin btn() {
  /* default / generic btn */
}

@mixin btn-success() { /* green-colored btn */ }
@mixin btn-warning() { /* yellow-colored btn */ }
@mixin btn-danger() { /* red-colored btn */}
@mixin btn-info() { /* blue-colored btn */}
```

I'm a bit dissatisfied, so I thought of asking your suggestion first hehe. :smile: 

Was I able to clear up the confusion? Sorry about that :smile:

**Comment by rstacruz** [comment]
seems just about right. so then you'd be able to do:

``` sass
.landing-super-hero-shot
  .button
    +btn
    +btn-success
```

this is outside the scope of rscss at the moment, which doesn't have any notes on mixin conventions.

**Comment by srph** [comment]
Actually, my bad. I never thought I could `@extend` "nested" selectors with SASS. I mistook `.btn.-inverse` as nested.
