### ISSUE TITLE
Tag selectors

### ISSUE THREAD

**Issue by richardbalaz** [rstacruz/rscss#21]
What in case, that I have in some div many paragraphs or anchors, should I use class or tag selection?

```
<div class="header-text">
<p>Lorem</p>
<p>Lorem</p>
<p>Lorem</p>
</div>
```

```
.header-text {
    p { color: black; }
}
```

Or:

```
<div class="header-text">
<p class="paragraph">Lorem</p>
<p class="paragraph">Lorem</p>
<p class="paragraph">Lorem</p>
</div>
```

```
.header-text {
    .paragraph { color: black; }
}
```

**Comment by rstacruz** [comment]
I think this is something our individual judgements should reign on. It's easy to say "Always use a class!", but if that gets in the way of your workflow (say, there are too many paragraphs) then it's probably best to just select them by tag.

As a more concrete example, Using `<h2 class='title'>` is typically sensible enough. `<p class='subtext'>` is also manageable for one paragraph below a heading. But in the case of `<div class='document-text'><p><p><p><p><p><p>...</div>`, it's probably too much to be add classes to each paragraph.

The rscss recommendation is _Avoid tag selectors_, not _Tag selectors are not allowed, ever_ :-)

**Comment by jeroenvisser101** [comment]
I feel like it's also important to note that if you think you're going to have different variants in the future, adding a class makes sense. If you're pretty sure that will not happen, using tag names is fine.

**Comment by richardbalaz** [comment]
Thank you for your advice! Best regards, Richard. :-)
