### ISSUE TITLE
Advise against using '&-modifier'

### ISSUE THREAD

**Issue by dan-gamble** [rstacruz/rscss#4]
As this makes search for selectors quite a pain in most if not all editors.

As much as i like this approach it makes refactoring a bit of a nightmare.

**Comment by fabiofl** [comment]
I also can see the problem. But I think it wouldn't be a huge problem if you use source maps.

Makes sense?

Also, if the idea is to keep each component on it's own file, you should have very clean, easy-to-maintain source files.

**Comment by dan-gamble** [comment]
No, source maps help greatly but when trying to find the selector for example in sublime `CMD+F` you won't be able to find it.

Like i said i do prefer the way you've put it, it just makes it a bit of a pain narrowing down the class by searching with your editor

**Comment by CydGoblin** [comment]
Would underscores `_` work better? maybe 2 underscores `__`

**Comment by darsain** [comment]
I don't understand the problem? I've tried normal Ctrl+F search, as well as Ctrl+R for Goto Symbol, and zero issues. Tried as well Ctrl+Shift+F (search in files) and again, zero issues.

It _would_ be quite bizarre if editor couldn't find strings with dashes in them.

---

I find this whole proposal awesome and I'm definitely gonna give it a shot in my next project. I'm kinda half way through as I'm already separating every reusable part into a stand alone component in its own file, but I've had issues with modifiers clashing with other (3rd party) stuff. This would definitely solve it, and look nice and meaningful. Nice crystallization of a style structure direction that I actually prefer :+1: :heart:

BEM and it's underscores and double-dashes is so ugly and verbose I can't even consider trying it.

**Comment by dan-gamble** [comment]
@darsain 
The problem isn't finding strings with a hyphen in. The problem is when you start nesting with the `&` selector like:

```
.foo {
    &-bar {}
    &-foo {}
}
```

In your html you use `.foo-bar` or `.foo-foo`. Now try and `CTRL-F` for `.foo-foo`. Nothing will show up. Now do this for every selector in a big project. Now hand it off to another guy who see's you have used `foo-foo` and goes to search for it but nothing comes up?

I agree the proposal is very good and BEM at times can look ugly as hell but the real benefit of it is usability. I'm happy to sacrifice some "Prettyness" to make my code alot more verbose and usable.

@Turqueso 
I feel like a double __ helps a bit as it should help with more unique searching but you still run into the problem i mentioned above.

**Comment by rstacruz** [comment]
The recommendation is `&.-bar`, not `&-bar`.

That is, you're looking to get `class="call-button -large"` (rscss style) and not `class="call-button call-button-large"` (bootstrap style).

**Comment by rstacruz** [comment]
Oh, I may have misinterpreted your issue—did you mean to suggest writing a section to advice against the `&-modifier` style?

**Comment by localpcguy** [comment]
`&.-bar` increases specificity, which is generally not preferred.  I understand the original comment, he was advising against using `&-modifier` syntax in Sass due to searchability issues. I found this is not that large of an issue in practice, you get used to searching for just the suffix and a logical CSS (Sass) structure will make it pretty obvious where you should be looking for the item in question.

**Comment by dan-gamble** [comment]
@rstacruz I was basically advising against doing:

```
.foo {
    &-bar {}
    &-foo {}
}
```

And instead write it as:

```
.foo-bar {}
.foo-foo {}
```

Just so if your project gets inherited down the line you can `cmd-click`, `navigation to declaration` or simply search for `foo-bar` and you would get a result in an `.scss` file instead of having no result or having to look in the `.css` file and following the sass comment back to the original position.

Like i've said before i prefer the 1st way, it makes sense to relate them under 1 scope (`.foo`) but it just makes finding the declaration a bit of a pain.

**Comment by rstacruz** [comment]
naming things as `.component_name--element` (like `.foo-bar` or `.sub-toolbar--label`) is something that wouldn't make it to rscss—moving into that territory would essentially make it into BEM.

**Comment by stramel** [comment]
@DanGamble89 I agree with @rstacruz. The syntax that you proposed reminds me of BEM. 

_Side Note:_ Using Atom I have never had any issue finding something like `&.-bar`. Searching `.-bar`, `-bar`, `bar` all work.

**Comment by polarathene** [comment]
While searching may be a bit more bothersome in some cases, a regex search should avoid the issue. Make sure your `.*` regex button in search is enabled(at least in Atom). Atom also has a JS regex parser far as I know so you need to use this work around: http://stackoverflow.com/questions/1068280/javascript-regex-multiline-flag-doesnt-work

Your regex search then becomes `component-name``[^]+``element` for example: `foo[^]+-bar`. You should be able to continue that pattern to something like `selector1[^]+selector2[^]+selector3` etc if needed.

It's the convention/pattern in use that makes this work well, so if anyone new comes on board or inherits the project, you should have such documented to make the pattern in use clear, thus no confusion when searching source files. I find the double dash/underscore of BEM to enforce that clarity better, though I guess the other approach with classes works too so long as you're mindful of nested collisions as described at the end of the readme advising to use `>` child selector to avoid.
