### ISSUE TITLE
About Simplifying nested components

### ISSUE THREAD

**Issue by exalted** [rstacruz/rscss#40]
In section [Simplifying nested components](https://github.com/rstacruz/rscss/blob/aa9a8d628067072dd83d91952727883001ed4c53/docs/nested-components.md#simplifying-nested-components) the example given is this:

``` html
<div class='search-form'>
  <input class='input' type='text'>
  <button class='search-button -red -large'></button>
</div>
```

It curious how the "search button" is labeled as a component (or a nested component in this example) rather than an element, such as:

``` html
<div class='search-form'>
  <input class='input' type='text'>
  <button class='searchbutton -red -large'></button>
</div>
```

... and then for the solution it's "converted" to an element with class `submit`. This is pretty confusing, because the solution not only suggesting using `@extend`, but also refactors the DOM. I know you shouldn't reach into nested components however, so the following is not good:

``` sass
.search-form {
  > .search-button { /* ... */ }
}
```

But then I don't quite follow how good is `@extend` as a solution to a non-problem in the first place. I am pretty confused.

I guess my question is pretty much aligned with https://github.com/rstacruz/rscss/issues/9 at this point, although I would like to hear more on this.

Thanks

**Comment by rstacruz** [comment]
>  I know you shouldn't reach into nested components however, so the following is not good:

good point, that should probably be changed; that wasn't a good example to begin with.
