### ISSUE TITLE
Homepage logo/search icon

### ISSUE THREAD

**Issue by smhutch** [rstacruz/rscss#41]
Found the magnifying glass icon on the rscss page rather confusing. Might just be a personal preference, but I expected it to open some sort of search functionality.

![rscss](https://cloud.githubusercontent.com/assets/7217244/13051857/6b2faed0-d3f3-11e5-858a-47e75eeada62.png)

**Comment by rstacruz** [comment]
haha... yes, i wasn't able to finish that one, sorry. I should get to it at some point. https://github.com/docpress/docpress/issues/38
