### ISSUE TITLE
CSS Structure: About glob matching for Less

### ISSUE THREAD

**Issue by mrmlnc** [rstacruz/rscss#53]
Chapter: https://github.com/rstacruz/rscss/blob/master/docs/css-structure.md#use-glob-matching

Maybe add information about Less?

https://github.com/just-boris/less-plugin-glob

**Comment by rstacruz** [comment]
Neat! If we include that though, it'd only be fair to add in the other ways
to do it in other languages:
- postcss-easy-import for postcss
- sass-rails for ruby
- brunch.io
- stylus
- ...and so on

Probably deserves an appendix page instead.

(On that note, I've no idea how it can be done with node-Sass, haha)

**Comment by mrmlnc** [comment]
For node-sass - https://github.com/lucasmotta/sass-glob-importer or https://npms.io/search?term=sass+glob (i use `gulp-sass-glob`)

Sounds rational. I close this issue.
