### ISSUE TITLE
Create wiki

### ISSUE THREAD

**Issue by rishabhranjit** [rstacruz/rscss#87]
A wiki would be nice.

If you want, I could make it.

**Comment by rstacruz** [comment]
Thanks for reaching out! There's an empty wiki here in GitHub (https://github.com/rstacruz/rscss/wiki), feel free to write any articles that might be of interest to the community.

**Comment by rishabhranjit** [comment]
Sorry to post again here, but I have been doing some work on the wiki (yes it's been forever since I asked to do it), and noticed that for some odd reason, adding to the wiki didn't put me on the contributor list.

It's nothing too big, just wondering if my changes were actually saving, or if they were local changes...

**Comment by rstacruz** [comment]
Yes its there! Thanks for your help, feel free to drop your name and link in there :)
