### ISSUE TITLE
rscss.io offline

### ISSUE THREAD

**Issue by WebMechanic** [rstacruz/rscss#89]
Hello,

as the title says.
I presume https://ricostacruz.com/rscss/ contains the same content. 
Maybe change the link in the repo description.

**Comment by SassNinja** [comment]
@rstacruz any update regarding this?

It's a bad first impression of RSCSS when the "official" website doesn't exists anymore. Replacing it with the url mentioned above would be great.

**Comment by rstacruz** [comment]
Hi all, https://ricostacruz.com/rscss is now the official site indeed. Thanks for the heads up, I've updated the repo description on GitHub.

**Comment by SassNinja** [comment]
@rstacruz thanks for updating the repo description

However you've missed the README which still links to the erroneous url:
https://github.com/rstacruz/rscss/blob/main/README.md?plain=1#L1

**Comment by rstacruz** [comment]
Thanks @SassNinja, fixed!
